package pt.tecnico.grpc.client;

/* these imported classes are generated by the hello-world-server contract */
import pt.tecnico.grpc.HelloWorld;
import pt.tecnico.grpc.HelloWorldServiceGrpc;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

public class HelloClient {

	public static void main(String[] args) throws Exception {
		System.out.println(HelloClient.class.getSimpleName());

		// receive and print arguments
		System.out.printf("Received %d arguments%n", args.length);
		for (int i = 0; i < args.length; i++) {
			System.out.printf("arg[%d] = %s%n", i, args[i]);
		}

		// check arguments
		if (args.length < 4) {
			System.err.println("Argument(s) missing!");
			System.err.printf("Usage: java %s host port numberOfServers listOfNames%n", HelloClient.class.getName());
			return;
		}

		final String host = args[0];
		final int port = Integer.parseInt(args[1]);
		final int numServers = Integer.parseInt(args[2]);
		final String[] names = args[3].split(",");

		// Must specify a name for each request sent to a server
		assert numServers == names.length;

		// Make a channel and a stub for each server
		String target;
		ManagedChannel[] channels = new ManagedChannel[numServers];
		HelloWorldServiceGrpc.HelloWorldServiceStub[] stubs = new HelloWorldServiceGrpc.HelloWorldServiceStub[numServers];
		for (int i = 0; i < numServers; i++) {
			target = host + ":" + (port + i);
			channels[i] = ManagedChannelBuilder.forTarget(target).usePlaintext().build();
			stubs[i] = HelloWorldServiceGrpc.newStub(channels[i]);
		}

		// Build the requests and make the calls using the stubs
		// Use the collector to save the responses
		HelloWorld.HelloRequest request;
		ResponseCollector collector = new ResponseCollector();
		for (int i = 0; i < numServers; i++) {
			request = HelloWorld.HelloRequest.newBuilder().setName(names[i]).build();
			stubs[i].greeting(request, new HelloObserver(collector));
		}

		// Wait for the responses and then print them to the command line
		collector.waitUntilAllReceived(numServers);
		System.out.println("Responses collected:\n- " + collector.getResponses());

		// A Channel should be shutdown before stopping the process
		// We can't use shutdownNow as it will cancel the asynchronous call
		System.out.println("Shutting down");
		for (ManagedChannel channel : channels) {
			channel.shutdown();
		}
	}

}
